spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect