version: "3.9"
services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "kanban"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
